apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-node
  namespace: default
  labels:
    app: cardano-node
spec:
  selector:
    matchLabels:
      app: cardano-node
  replicas: 1
  template:
    metadata:
      labels:
        app: cardano-node
    spec:
      containers:
      - name: cardano-node
        image: blinklabs/cardano-node:main
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
          name: node-port
        - containerPort: 12788
          name: prometheus
        env:
        - name: NETWORK
          value: "mainnet"
        volumeMounts:
        - name: node-data
          mountPath: /data
      volumes:
      - name: node-data
        emptyDir: {}
