apiVersion: v1
kind: Service
metadata:
  name: cardano-node
  namespace: default
  labels:
    app: cardano-node
spec:
  clusterIP: None
  selector:
    app: cardano-node
  ports:
  - name: node-port
    port: 3001
    targetPort: 3001
  - name: prometheus
    port: 12788
    targetPort: 12788
