apiVersion: v1
kind: Service
metadata:
  name: cardano-node-indexer-ui
  namespace: default
  labels:
    app: yaci-indexer-ui
spec:
  selector:
    app: yaci-indexer-ui
  ports:
  - name: http
    port: 5173
    targetPort: 5173
