apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-node-store-ui
  namespace: default
  labels:
    app: yaci-store-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaci-store-ui
  template:
    metadata:
      labels:
        app: yaci-store-ui
    spec:
      containers:
      - name: yaci-store-ui
        image: bloxbean/yaci-viewer:0.10.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
          name: http
        env:
        - name: PUBLIC_STORE_BASE_URL
          value: "http://localhost:8080/api/v1"
        - name: PUBLIC_STORE_WS_URL
          value: "ws://localhost:8080/ws/liveblocks"
