apiVersion: v1
kind: Service
metadata:
  name: cardano-node-store
  namespace: default
  labels:
    app: yaci-store
spec:
  selector:
    app: yaci-store
  ports:
  - name: http
    port: 8080
    targetPort: 8080
